version: '3'
services: 
  blockscout:
    image: aleksn7/blockscout:v1.4
    # container_name: blockscout
    ports:
      - 127.0.0.1:4000:4000
    environment: 
      - MIX_ENV=prod
      - NETWORK=CSE
      - SUBNETWORK=Cesoie
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
      - ETHEREUM_JSONRPC_TRACE_URL=http://geth:8545 
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?ssl=false
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORT=4000
      - COIN=ETH
      - BLOCKSCOUT_HOST=cesoie.net
      - BLOCKSCOUT_PROTOCOL=https
      - BLOCK_TRANSFORMER=clique
      - ENABLE_TXS_STATS=true
      - GAS_PRICE=1
      - BLOCKSCOUT_VERSION=CSE1.4
      - LOGO=/images/mylogo.png
      - LOGO_FOOTER=/images/mylogo.png
    links: 
      - postgres
      - geth
      - blockscout-migrations
    command: mix phx.server
    restart: always

  blockscout-migrations:
    image: aleksn7/blockscout:v1.4
    # container_name: blockscout-migrations
    environment: 
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?ssl=false
    links:
      - postgres
      - geth
    command: mix do ecto.create, ecto.migrate

  postgres:
    image: postgres:latest
    # container_name: postgres
    ports:
     - 127.0.0.1:5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  geth:
    image: aleksn7/cesoie-geth:v1.1
    ## container_name: geth
    ports: 
      - 127.0.0.1:8545:8545
      - 127.0.0.1:8546:8546
      - 30303:30303
    volumes:
      - geth-data:/geth
    command:
      ./geth 
      --syncmode 'full' 
      --networkid 4071505 
      --gcmode=archive 
      --datadir /geth/blockchain  
      --http 
      --http.port 8545 
      --http.addr 0.0.0.0 
      --http.corsdomain "*" 
      --http.api "debug,eth,net,web3,personal,miner,txpool" 
      --http.vhosts="*" 
      --rpc.allow-unprotected-txs 
      --ws 
      --ws.addr 0.0.0.0 
      --ws.port 8546 
      --ws.api "debug,eth,net,web3,personal,miner,txpool" 
      --ws.origins "*" 
      --port 30303 
      --bootnodes "${ENODE_ADDRESS}"
    restart: always
  
  nginx:
    image: nginx:latest
    # container_name: nginx
    ports: 
      - 443:443
      - 80:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Certs/fullchain.pem:/fullchain.pem:ro
      - ./Certs/privkey.pem:/privkey.pem:ro
    links:
      - geth
      - blockscout
    restart: always

  node_exporter:
    image: prom/node-exporter
    # container_name: node_exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always

volumes:
  pg-data:
  geth-data:
    
